// models/ScamReport.js

const mongoose = require("mongoose");

/*
Scam Report Schema

Purpose:
Defines how scam reports are stored in the database.

This structure becomes:
- Your dataset
- Your labeling system
- Your AI training data foundation
*/

const ScamReportSchema = new mongoose.Schema({
  
  // Scam message submitted by user
  message: {
    type: String,
    required: true,
    trim: true
  },

  // Risk score generated by detection engine
  riskScore: {
    type: Number,
    default: 0
  },

  // Scam category labeling system
  category: {
    type: String,
    enum: [
      "phishing",
      "investment_scam",
      "impersonation",
      "lottery_scam",
      "loan_fraud",
      "crypto_scam",
      "other"
    ],
    default: "other"
  },

  // Platform where scam occurred
  platform: {
    type: String,
    default: "unknown"
  },

  // Country or region (future heatmaps)
  location: {
    type: String,
    default: "unknown"
  },

  // Whether message confirmed as scam
  isVerified: {
    type: Boolean,
    default: false
  },

  // AI prediction confidence (future)
  confidence: {
    type: Number,
    default: 0
  },

  // Timestamp of report submission
  createdAt: {
    type: Date,
    default: Date.now
  }

});

/*
Export Model

This allows:
- Saving scam reports
- Reading scam reports
- Building datasets
*/

module.exports = mongoose.model("ScamReport", ScamReportSchema);
